<#
.SYNOPSIS
Builds a replacement byte sequence dynamically from extracted instruction metadata.

.DESCRIPTION
Constructs a replacement byte array using instruction metadata extracted from
a validated binary signature context.

The generated sequence preserves structural information from the original
instruction stream by dynamically reusing:
    - Register encoding extracted from the ModR/M byte
    - Original displacement bytes
    - Conditional branch context

Replacement layout:
    [B8+reg] [imm32] [89] [ModRM] [disp32] [90] [EB?]

The resulting sequence size depends on the detected branch type:
    - jz  : 12 bytes
    - jne : 13 bytes

.PARAMETER ModRM
ModR/M byte extracted from the validated instruction context.

Expected encoding:
    mod = 10b (disp32 addressing mode)

.PARAMETER Displacement
Four-byte displacement extracted from the validated instruction context.

.PARAMETER JumpType
Conditional branch type identified during signature analysis.

Supported values:
    - jz
    - jne

.EXAMPLE
PS C:\> New-ReplacementByte -ModRM 0x81 -Displacement @(0x38,0x06,0x00,0x00) -JumpType 'jz'

.INPUTS
None

.OUTPUTS
System.Byte[]

.NOTES
This function only generates replacement byte sequences.
It does not modify binaries or perform write operations.
#>
function New-ReplacementByte {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
        'PSUseShouldProcessForStateChangingFunctions',
        '',
        Justification = 'ShouldProcess is handled by the calling public function.'
    )]
    [CmdletBinding()]
    [OutputType([byte[]])]
    param(
        [Parameter(Mandatory)]
        [byte]$ModRM,

        [Parameter(Mandatory)]
        [ValidateCount(4, 4)]
        [byte[]]$Displacement,

        [Parameter(Mandatory)]
        [ValidateSet('jz', 'jne')]
        [string]$JumpType
    )

    process {
        try {
            # Validate ModR/M addressing mode:
            # mod = 10b -> disp32 memory addressing
            if (($ModRM -band 0xC0) -ne 0x80) {
                $ex = [System.ArgumentException]::new(
                    ("Unsupported ModR/M encoding: 0x{0:X2}" -f $ModRM)
                )

                $err = [System.Management.Automation.ErrorRecord]::new(
                    $ex,
                    "UnsupportedModRMEncoding",
                    [System.Management.Automation.ErrorCategory]::InvalidData,
                    $ModRM
                )

                $PSCmdlet.ThrowTerminatingError($err)
            }

            # Immediate value written during sequence transformation
            [byte[]]$replacementValue = 0x00, 0x01, 0x00, 0x00

            # Extract register field from ModR/M bits [5:3]
            [byte]$registerField = ($ModRM -shr 3) -band 0x07

            # mov r32, imm32 opcode
            [byte]$movImmediateOpcode = 0xB8 + $registerField

            [System.Collections.Generic.List[byte]]$result =
                [System.Collections.Generic.List[byte]]::new(14)

            # mov r32, imm32
            $result.Add($movImmediateOpcode)
            foreach ($byteValue in $replacementValue) {
                $result.Add($byteValue)
            }

            # mov [base+disp32], r32
            $result.Add(0x89)
            $result.Add($ModRM)
            foreach ($byteValue in $Displacement) {
                $result.Add($byteValue)
            }

            # nop
            $result.Add(0x90)

            # jmp rel8 (conditional branch replacement context only)
            if ($JumpType -eq 'jne') {
                $result.Add(0xEB)
            }

            [int]$expectedLength = if ($JumpType -eq 'jne') {
                13
            } else {
                12
            }

            if ($result.Count -ne $expectedLength) {
                $ex = [System.InvalidOperationException]::new((
                    "Generated byte sequence length mismatch. " +
                    "Expected: {0}, Actual: {1}" -f $expectedLength, $result.Count
                ))

                $err = [System.Management.Automation.ErrorRecord]::new(
                    $ex,
                    "ReplacementSequenceLengthMismatch",
                    [System.Management.Automation.ErrorCategory]::InvalidResult,
                    $result
                )

                $PSCmdlet.ThrowTerminatingError($err)
            }

            return [byte[]]$result.ToArray()
        } catch {
            $err = [System.Management.Automation.ErrorRecord]::new(
                $_.Exception,
                "ReplacementByteGenerationFailed",
                [System.Management.Automation.ErrorCategory]::InvalidOperation,
                $ModRM
            )

            $PSCmdlet.ThrowTerminatingError($err)
        }
    }
}
